default:
  rotate_count: 10
  output_path: streams/
  quality: best
  timezone: Asia/Seoul

streams:
  overwatchleague:
    url: https://www.twitch.tv/overwatchleague
    interval:
      mon:
        22:25-23:59: 60
      tue:
        22:25-23:59: 60
      wed:
        22:25-23:59: 60
      thu:
        22:25-23:59: 60
      fri:
        22:25-23:59: 60
      sat:
        22:25-23:59: 60
      sun:
        22:25-23:59: 60
      00:00-23:59: 600

  aflol:
    url: http://bj.afreecatv.com/aflol
    interval:
      wed:
        19:45-21:00: 60